---
- hosts: all
  remote_user: ubuntu
  become: yes
  become_method: sudo
  tasks:
    - name: 'copy ssh key'
      template:
        src: '../key/id_rsa.pub'
        dest: '/home/ubuntu/.ssh/id_rsa.pub'
        mode: 0600
        owner: ubuntu
        group: ubuntu

    - name: 'create authorized_keys file'
      shell: "cat /home/ubuntu/.ssh/id_rsa.pub >> /home/ubuntu/.ssh/authorized_keys"
      args:
          executable: /bin/bash

    - name: 'download minikube'
      get_url:
        url: 'https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64'
        sha256sum: 'dfe361f86288a4cedcdc3bffbbe5b4716c7ee19cbb82d70696b0f20596a15c65'
        dest: /usr/local/bin/minikube
        mode: 0755
        owner: ubuntu
        group: ubuntu

    - name: 'download k8s'
      get_url:
        url: "https://storage.googleapis.com/kubernetes-release/release/v1.10.3/bin/linux/amd64/kubectl"
        sha256sum: '62893257193f9e848f383055993e63166ab67bf872c85e896ce9b9167ba85403'
        dest: /usr/local/bin/kubectl
        mode: 0755
        owner: ubuntu
        group: ubuntu


    - name: 'copy minikube envs'
      copy:
        src: ../scripts/env-minikube.sh
        dest: /etc/profile.d/minikube.sh
        owner: ubuntu
        group: ubuntu
        mode: 0744

    - name: 'execute source'
      shell: "source /etc/profile.d/minikube.sh"
      args:
          executable: /bin/bash